"""Tests for the planner workflow's pydantic I/O schemas (M3 Task 02).

Covers the acceptance criteria from
``design_docs/phases/milestone_3_first_workflow/task_02_planner_schemas.md``.
"""

from __future__ import annotations

import pytest
from pydantic import ValidationError

from ai_workflows.workflows.planner import PlannerInput, PlannerPlan, PlannerStep


def _valid_step(index: int = 1) -> dict[str, object]:
    return {
        "index": index,
        "title": "Draft landing copy",
        "rationale": "Need a first-pass hero section to align on tone.",
        "actions": ["Sketch hero headline", "List primary CTAs"],
    }


def _valid_plan() -> dict[str, object]:
    return {
        "goal": "Ship the marketing page.",
        "summary": "Three-step delivery of the static hero + CTA page.",
        "steps": [_valid_step()],
    }


class TestPlannerInput:
    def test_minimal_payload_defaults(self) -> None:
        model = PlannerInput(goal="Ship it")
        assert model.goal == "Ship it"
        assert model.context is None
        assert model.max_steps == 10

    def test_empty_goal_rejected(self) -> None:
        with pytest.raises(ValidationError):
            PlannerInput(goal="")

    def test_goal_length_cap(self) -> None:
        with pytest.raises(ValidationError):
            PlannerInput(goal="x" * 4001)

    def test_context_length_cap(self) -> None:
        with pytest.raises(ValidationError):
            PlannerInput(goal="Ship it", context="x" * 4001)

    def test_max_steps_lower_bound(self) -> None:
        with pytest.raises(ValidationError):
            PlannerInput(goal="Ship it", max_steps=0)

    def test_max_steps_upper_bound(self) -> None:
        with pytest.raises(ValidationError):
            PlannerInput(goal="Ship it", max_steps=26)

    def test_max_steps_boundary_values_allowed(self) -> None:
        assert PlannerInput(goal="Ship it", max_steps=1).max_steps == 1
        assert PlannerInput(goal="Ship it", max_steps=25).max_steps == 25


class TestPlannerStep:
    def test_minimal_valid_step(self) -> None:
        step = PlannerStep(**_valid_step())  # type: ignore[arg-type]
        assert step.index == 1
        assert step.actions == ["Sketch hero headline", "List primary CTAs"]

    def test_index_must_be_positive(self) -> None:
        payload = _valid_step()
        payload["index"] = 0
        with pytest.raises(ValidationError):
            PlannerStep(**payload)  # type: ignore[arg-type]

    def test_actions_must_be_non_empty(self) -> None:
        payload = _valid_step()
        payload["actions"] = []
        with pytest.raises(ValidationError):
            PlannerStep(**payload)  # type: ignore[arg-type]

    def test_actions_upper_bound(self) -> None:
        payload = _valid_step()
        payload["actions"] = [f"action-{i}" for i in range(11)]
        with pytest.raises(ValidationError):
            PlannerStep(**payload)  # type: ignore[arg-type]

    def test_title_and_rationale_required(self) -> None:
        payload = _valid_step()
        payload["title"] = ""
        with pytest.raises(ValidationError):
            PlannerStep(**payload)  # type: ignore[arg-type]


class TestPlannerPlan:
    def test_minimal_valid_plan_round_trips(self) -> None:
        plan = PlannerPlan.model_validate(_valid_plan())
        dumped = plan.model_dump()
        again = PlannerPlan.model_validate(dumped)
        assert again == plan

    def test_steps_must_be_non_empty(self) -> None:
        payload = _valid_plan()
        payload["steps"] = []
        with pytest.raises(ValidationError):
            PlannerPlan.model_validate(payload)

    def test_steps_upper_bound(self) -> None:
        payload = _valid_plan()
        payload["steps"] = [_valid_step(i) for i in range(1, 27)]
        with pytest.raises(ValidationError):
            PlannerPlan.model_validate(payload)

    def test_extra_top_level_field_rejected(self) -> None:
        payload = _valid_plan()
        payload["disclaimer"] = "Generated by an LLM."
        with pytest.raises(ValidationError):
            PlannerPlan.model_validate(payload)

    def test_empty_summary_rejected(self) -> None:
        payload = _valid_plan()
        payload["summary"] = ""
        with pytest.raises(ValidationError):
            PlannerPlan.model_validate(payload)

    def test_empty_goal_rejected(self) -> None:
        payload = _valid_plan()
        payload["goal"] = ""
        with pytest.raises(ValidationError):
            PlannerPlan.model_validate(payload)
