"""Tests for the planner workflow's pydantic I/O schemas (M3 Task 02).

Covers the acceptance criteria from
``design_docs/phases/milestone_3_first_workflow/task_02_planner_schemas.md``
and the schema-simplification amendment from
``design_docs/phases/milestone_3_first_workflow/task_07b_planner_schema_simplify.md``.

Per T07b, ``PlannerStep`` and ``PlannerPlan`` drop their per-field
``min_length`` / ``max_length`` / ``ge`` bounds so that
:meth:`PlannerPlan.model_json_schema` stays within Gemini's
structured-output complexity budget. Type validation (``int`` / ``str`` /
``list``) and closed-world (``extra="forbid"``) enforcement remain. The
removed bounds are prompt-enforced via ``PlannerInput.max_steps``.
"""

from __future__ import annotations

import pytest
from pydantic import ValidationError

from ai_workflows.workflows.planner import PlannerInput, PlannerPlan, PlannerStep


def _valid_step(index: int = 1) -> dict[str, object]:
    return {
        "index": index,
        "title": "Draft landing copy",
        "rationale": "Need a first-pass hero section to align on tone.",
        "actions": ["Sketch hero headline", "List primary CTAs"],
    }


def _valid_plan() -> dict[str, object]:
    return {
        "goal": "Ship the marketing page.",
        "summary": "Three-step delivery of the static hero + CTA page.",
        "steps": [_valid_step()],
    }


class TestPlannerInput:
    def test_minimal_payload_defaults(self) -> None:
        model = PlannerInput(goal="Ship it")
        assert model.goal == "Ship it"
        assert model.context is None
        assert model.max_steps == 10

    def test_empty_goal_rejected(self) -> None:
        with pytest.raises(ValidationError):
            PlannerInput(goal="")

    def test_goal_length_cap(self) -> None:
        with pytest.raises(ValidationError):
            PlannerInput(goal="x" * 4001)

    def test_context_length_cap(self) -> None:
        with pytest.raises(ValidationError):
            PlannerInput(goal="Ship it", context="x" * 4001)

    def test_max_steps_lower_bound(self) -> None:
        with pytest.raises(ValidationError):
            PlannerInput(goal="Ship it", max_steps=0)

    def test_max_steps_upper_bound(self) -> None:
        with pytest.raises(ValidationError):
            PlannerInput(goal="Ship it", max_steps=26)

    def test_max_steps_boundary_values_allowed(self) -> None:
        assert PlannerInput(goal="Ship it", max_steps=1).max_steps == 1
        assert PlannerInput(goal="Ship it", max_steps=25).max_steps == 25


class TestPlannerStep:
    def test_minimal_valid_step(self) -> None:
        step = PlannerStep(**_valid_step())  # type: ignore[arg-type]
        assert step.index == 1
        assert step.actions == ["Sketch hero headline", "List primary CTAs"]

    def test_type_coercion_preserved(self) -> None:
        payload = _valid_step()
        payload["index"] = "not-an-int"
        with pytest.raises(ValidationError):
            PlannerStep(**payload)  # type: ignore[arg-type]


class TestPlannerPlan:
    def test_minimal_valid_plan_round_trips(self) -> None:
        plan = PlannerPlan.model_validate(_valid_plan())
        dumped = plan.model_dump()
        again = PlannerPlan.model_validate(dumped)
        assert again == plan

    def test_extra_top_level_field_rejected(self) -> None:
        payload = _valid_plan()
        payload["disclaimer"] = "Generated by an LLM."
        with pytest.raises(ValidationError):
            PlannerPlan.model_validate(payload)


def test_plannerplan_json_schema_has_no_state_space_bounds() -> None:
    """T07b AC-2 — ``model_json_schema()`` contains no bound keywords.

    Gemini's structured-output admission rejects schemas whose combined
    ``minLength`` / ``maxLength`` / ``minItems`` / ``maxItems`` /
    ``minimum`` / ``maximum`` / ``exclusiveMinimum`` / ``exclusiveMaximum``
    constraints push the serving state space past its budget (seen
    2026-04-20 on the pre-T07b ``PlannerPlan``: ~25 × nested bounded
    arrays × multiple bounded strings × integer ``ge`` triggered
    ``BadRequestError 400 — schema produces a constraint that has too
    many states for serving``). This test is the compile-time pin that
    keeps the emitted schema bound-free so Gemini can admit it.

    ``additionalProperties: false`` (from ``extra="forbid"``) is not a
    state-space bound — Gemini accepts it at every depth in
    ``ExplorerReport``, which has always shipped with it.
    """
    import json

    banned = {
        "minLength",
        "maxLength",
        "minItems",
        "maxItems",
        "minimum",
        "maximum",
        "exclusiveMinimum",
        "exclusiveMaximum",
    }
    schema = PlannerPlan.model_json_schema()
    blob = json.dumps(schema)
    for keyword in banned:
        assert keyword not in blob, (
            f"{keyword!r} present in PlannerPlan.model_json_schema() — "
            f"Gemini's structured-output budget rejects bounded schemas. "
            f"Full schema: {blob}"
        )
