"""Surface-check helper — probe which Task-tool response fields are exposed.

Task: M20 Task 22 — Per-cycle token telemetry per agent (surface-check pre-step,
  per audit M7 requirement).
Relationship: Standalone script called once before enabling production telemetry
  capture.  Writes ``runs/m20_t22_surface_check.txt`` as the audit trail so the
  auditor can verify which fields are available on the current Claude Code build.

Extensible per carry-over L1 round 2 (2026-04-27): the helper probes three sets
of fields to cover T22 (token telemetry), T27 (tool-result clearing via
``context_management.edits`` + ``clear_tool_uses_20250919``).  T28 was deferred
(``nice_to_have.md §24``), so no T28 probe is included.

Usage::

    python scripts/orchestration/check_task_response_fields.py [--output PATH]

    # Default output: runs/m20_t22_surface_check.txt
    python scripts/orchestration/check_task_response_fields.py

    # Custom output path (for tests)
    python scripts/orchestration/check_task_response_fields.py \\
        --output /tmp/surface_check.txt

The script does NOT make live API calls.  It documents which fields the
orchestrator *should* look for in Task-tool responses; it serves as a structured
reference for the auditor to verify against actual Claude Code behaviour at
task-close time.  The per-field availability judgement is populated by the
orchestrator after a real Task spawn; this script generates the template.
"""

from __future__ import annotations

import argparse
import sys
from datetime import UTC, datetime
from pathlib import Path

# ---------------------------------------------------------------------------
# Field registry
# ---------------------------------------------------------------------------

# Each entry is a tuple:
#   (field_name, category, notes)
#
# category:
#   "T22"  — token telemetry (T22's primary scope)
#   "T27"  — tool-result clearing surface (T27's scope; probed here for
#             extensibility per carry-over L1 round 2)
#
# notes: human-readable description of what the field is and how to verify.

FIELDS_TO_PROBE: list[tuple[str, str, str]] = [
    # --- T22: token telemetry ---
    (
        "input_tokens",
        "T22",
        "Total input tokens consumed by the Task spawn. Expected to be present "
        "in Task response metadata or via Claude Code usage dashboard. "
        "Fallback: regex proxy (len(re.findall(r'\\S+', text)) * 1.3).",
    ),
    (
        "output_tokens",
        "T22",
        "Total output tokens generated by the Task spawn. Same source as "
        "input_tokens. Fallback: word-count proxy on returned text.",
    ),
    (
        "cache_creation_input_tokens",
        "T22",
        "Tokens written to the cache during this spawn. Present only if "
        "Claude Code's Task tool exposes cache telemetry. If absent, record as null; "
        "T23 (cache-breakpoint discipline) will downgrade to STOP-AND-ASK.",
    ),
    (
        "cache_read_input_tokens",
        "T22",
        "Tokens read from the cache during this spawn (cache-hit count). "
        "Present only if Task tool exposes cache telemetry. If absent, record as null.",
    ),
    # --- T27: tool-result clearing ---
    (
        "context_management.edits",
        "T27",
        "Presence of the ``context_management.edits`` field in Task response "
        "payload (introduced with the ``clear_tool_uses_20250919`` strategy). "
        "T27 uses this to detect whether tool-result clearing is active and to "
        "compute the effective keep-window size. Absent on builds before "
        "2025-09-19. Record as: present / absent / unknown.",
    ),
    (
        "clear_tool_uses_20250919_strategy_available",
        "T27",
        "Whether the ``clear_tool_uses_20250919`` context-management strategy "
        "can be activated for long Auditor runs.  Verify by checking Claude Code "
        "release notes for the build date.  T27 will STOP-AND-ASK at land time "
        "if this strategy is unavailable.",
    ),
]


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------

def build_report(output_path: Path) -> str:
    """Build the surface-check report text.

    Args:
        output_path: The path this report will be written to (for self-reference).

    Returns:
        Markdown-formatted report text.
    """
    ts = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines: list[str] = [
        "# M20 T22 Surface-check report",
        "",
        f"Generated: {ts}",
        f"Output path: {output_path}",
        "",
        "## Purpose",
        "",
        "This file documents which Task-tool response fields are available on the",
        "current Claude Code build.  The orchestrator populates the 'Status' column",
        "after a real Task spawn; this template provides the field list and guidance.",
        "",
        "T22 (token telemetry): uses input_tokens, output_tokens,",
        "cache_creation_input_tokens, cache_read_input_tokens.",
        "",
        "T27 (tool-result clearing): uses context_management.edits and the",
        "clear_tool_uses_20250919 strategy flag.",
        "",
        "T28 (compact_20260112 evaluation): DEFERRED (nice_to_have.md §24);",
        "no surface probe included.",
        "",
        "## Field availability",
        "",
        "| Field | Category | Status | Notes |",
        "| --- | --- | --- | --- |",
    ]

    for field_name, category, notes in FIELDS_TO_PROBE:
        # Status is always "unknown" in the generated template;
        # the orchestrator fills it in after a real Task spawn.
        lines.append(
            f"| `{field_name}` | {category} | unknown — populate after Task spawn | {notes} |"
        )

    lines.extend([
        "",
        "## T22 telemetry decision",
        "",
        "Fill in after probing:",
        "",
        "- **If cache-* fields ARE exposed:** T22 ships full — all four token fields captured.",
        "- **If cache-* fields are NOT exposed:** T22 captures input_tokens + output_tokens",
        "  only; cache_creation_input_tokens and cache_read_input_tokens recorded as null.",
        "  T23 downgrades to STOP-AND-ASK at land time.",
        "- **If surface is partial:** T22 captures available subset; null-fills the rest.",
        "",
        "## T27 tool-result clearing decision",
        "",
        "Fill in after probing:",
        "",
        "- **If context_management.edits IS present:** T27 ships with ``keep`` window 3–5.",
        "- **If context_management.edits is NOT present:** T27 STOP-AND-ASK at land time —",
        "  the clearing strategy is unavailable on this Claude Code build.",
        "",
        "## Audit trail",
        "",
        "This file is written by ``scripts/orchestration/check_task_response_fields.py``",
        "and lives at ``runs/m20_t22_surface_check.txt`` (gitignored under runs/).  The",
        "auditor verifies it exists and that the orchestrator populated the Status column",
        "before declaring T22 and T27 land-ready.",
        "",
    ])

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# CLI entry-point
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> None:
    """Write the surface-check report to the output path.

    Args:
        argv: Optional argument list (defaults to ``sys.argv[1:]``).
    """
    parser = argparse.ArgumentParser(
        prog="check_task_response_fields.py",
        description=(
            "Generate the Task-tool surface-check template for T22 (token telemetry) "
            "and T27 (tool-result clearing).  The orchestrator populates field status "
            "after a real Task spawn."
        ),
    )
    parser.add_argument(
        "--output",
        default="runs/m20_t22_surface_check.txt",
        help="Output path for the surface-check report (default: runs/m20_t22_surface_check.txt)",
    )
    args = parser.parse_args(argv)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    report_text = build_report(output_path)

    try:
        output_path.write_text(report_text, encoding="utf-8")
    except OSError as exc:
        print(f"check_task_response_fields: write error — {exc}", file=sys.stderr)
        sys.exit(1)

    print(f"Surface-check report written to: {output_path}")
    print("Next step: run a single Task spawn and populate the 'Status' column in the report.")


if __name__ == "__main__":
    main()
